### ISSUE TITLE
Specifying `CONFIGURATION_BUILD_DIR` breaks implicit dependencies

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/vim-xcodebuild#32]
ffs how is this so awful?

xcodebuild doesn't find implicit dependencies the same way Xcode finds implicit dependencies so it's super unreliable. This really fucking sucks, and means that users would either have to avoid implicit dependencies (ugh) or... I have no idea. I don't know how else to fix this.

**Comment by gfontenot** [comment]
oh good, this issue exists.

Imagine a world where Xcode just used xcodebuild under the covers
what a world
what a world that would be

**Comment by gfontenot** [comment]
Seems like it's our custom build directory that's fucking with the ability to find implicit dependencies.

**Comment by gfontenot** [comment]
Renaming this because I need to re-think what I'm doing here.

The high level goal behind #26 was to make it easier to add a `Run` command by ensuring that built products were sent to a specific location. However, this also makes it _impossible_ to build/test apps using implicit dependencies.

We should really be able to do both. I think it might make more sense to kill `CONFIGURATION_BUILD_DIR` and find another way to find the built app when we add `XRun`

**Comment by DorianListens** [comment]
Is it possible that the relative path is the issue here? I'm not sure of another way to find the build directory programatically, so it'd be great if it could be customized like this.

Extracting an absolute path should be relatively trivial with a shell script, but I wanted to check if you'd already experimented with this before implementing it myself.

http://stackoverflow.com/questions/29660505/xcodebuild-linker-failing-when-custom-output-directory-provided

**Comment by gfontenot** [comment]
No, it has to do with framework search paths I think.

Either way, I don't think this is needed at all. It was based on some faulty assumptions.
