### ISSUE TITLE
Consider integrating SourceKittenDaemon for code completion

### ISSUE THREAD

**Issue by DorianListens** [gfontenot/vim-xcodebuild#45]
Very possibly out of scope for this project, but one of the main advantages of working in Xcode is code completion. SourceKittenDaemon seems to provide the main pieces for getting this to work from inside of vim, which would make Xcode.vim an extremely compelling alternative to Xcode itself.

https://github.com/terhechte/SourceKittenDaemon

**Comment by gfontenot** [comment]
I've tried this personally, and I think @keith actually worked up a prototype? I couldn't really get it to work, but I think it's really interesting. I do agree that it's probably out of scope for this particular project, though. It's possible that `xcode.vim` is too broad a name, and will only lead to the kind of bloat Xcode.app itself suffers from.

**Comment by DorianListens** [comment]
Perhaps `xcodebuild.vim` is maybe a more appropriate name? Please feel free to close this, I just ran into the SKD project again and figured I'd bring it up.

**Comment by keith** [comment]
I did make a plugin for this. https://github.com/keith/sourcekittendaemon.vim It actually seems to work alright. There are some problems with it in general though.

First source kitten daemon doesn't currently support workspaces, meaning projects using CocoaPods or workspaces for other reasons are out of the question.

Second sourcekitten doesn't seem to cover all the completion cases because sourcekit itself apparently doesn't handle them all. I haven't dug into why in apple/swift yet, but many useful completion cases will not work because sourcekit doesn't respond with them. See https://github.com/jpsim/SourceKitten/issues/113 for some conversation about that.

Lastly there have been some performance problems with both of those in general. Maybe with vim 8 (or if we tried to focus on neovim) we could utilize some of the async functionality, but I haven't dug into that much either.

</braindump>

**Comment by DorianListens** [comment]
Thanks @keith for the brain dump, I'll experiment with this and see how much those limitations impact me.

**Comment by gfontenot** [comment]
> Perhaps `xcodebuild.vim` is maybe a more appropriate name?

That's actually what it used to be, but has actually grown a bit beyond just that already. And I fully intend to support running builds in the simulator and whatnot whenever I get time to work on that, so it'll make even less sense.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this. I do want something like this, but feel like a separate plugin would be a better fit.
